import { motion } from "motion/react";
import { Shield, ChevronRight } from "lucide-react";

const SECTIONS = [
  {
    title: "Information We Collect",
    content: `We are committed to respecting Your online privacy. We further recognize Your need for appropriate protection and management of any Personal Information You share with us. We may collect the following information:

- Personal data including but not limited to Name, Phone Number, Email ID, Date of Birth, Gender, City, Geo-location, Photo.
- Tracking Information such as, but not limited to the IP address of your device and Device ID when connected to the Internet.

This privacy policy also applies to data we collect from users who are not registered as members of this website, including browsing behaviour, pages viewed etc.`,
  },
  {
    title: "Our Use of Your Information",
    content: `The information provided by you shall be used to provide and improve the service for you and all users:

- To provide you with services on your request.
- For maintaining an internal record.
- For enhancing the Services provided.
- For maintaining record under the legal and statutory provisions.

We will not sell, license or trade Your personal information. We will not share your personal information with others unless they are acting under our instructions or we are required to do so by law.`,
  },
  {
    title: "How Information Is Collected",
    content: `Before or at the time of collecting personal information, we will identify the purposes for which information is being collected. We will collect and use your personal information solely to fulfil those purposes specified by us, within the scope of the consent of the individual concerned or as required by law.

We will only retain personal information as long as necessary for the fulfilment of those purposes. We will collect personal information by lawful and fair means and with the knowledge and consent of the individual concerned.`,
  },
  {
    title: "Cookies",
    content: `A cookie is a small file of letters and numbers that we store on your browser or the hard drive of your computer if you agree. By continuing to browse the site, you are agreeing to our use of cookies.

1. Strictly necessary cookies — Required for the operation of our website.
2. Analytical/performance cookies — Allow us to recognize and count the number of visitors.
3. Functionality cookies — Used to recognize you when you return to our website.
4. Targeting cookies — Record your visit to our website, the pages you have visited and the links you have followed.`,
  },
  {
    title: "Google Analytics",
    content: `We use Google Analytics to help us understand how you make use of our content and work out how we can make things better. These cookies may follow all visitors of the website and collect anonymous data on where they have come from, which pages they visit, and how long they spend on the site.

The information generated by the cookie about the use of the website, including IP address, may be transmitted to and stored by Google on servers in the United States.`,
  },
  {
    title: "External Links on the Website",
    content: `The website may include advertisements, hyperlinks to other websites or resources. We have no control over any other website or resources or contents available on these other websites.

You acknowledge and agree that we are not responsible for the availability of any such external sites or resources, and do not endorse any advertising, services or other materials on or available from such website or resources.`,
  },
  {
    title: "Permission and Access from the Device",
    content: `The website requires permission to access the following features:

- Location
- Camera
- Device Storage
- SMS
- PDF Viewer`,
  },
  {
    title: "Your Rights",
    content: `Unless subject to an exemption, you have the following rights concerning your data:

- The right to request a copy of your data which we hold about you.
- The right to request for any correction to any personal data if it is found to be inaccurate or out of date.
- The right to withdraw Your consent to the processing at any time.
- The right to object to the processing of personal data.
- The right to complain about a supervisory authority.`,
  },
  {
    title: "Confidentiality",
    content: `You further acknowledge that the website may contain information that is designated confidential by us and that you shall not disclose such information without our prior written consent.

Your information is regarded as confidential and therefore will not be divulged to any third party, unless if legally required to do so to the appropriate authorities. We will not sell, share, or rent your personal information to any third party or use your e-mail address for unsolicited mail.`,
  },
  {
    title: "Security",
    content: `We treat data as an asset that must be protected against loss and unauthorized access. We employ many different security techniques to protect such data from unauthorized access by members inside and outside the Firm.

We follow generally accepted industry standards to protect the Personal Information submitted to us and information that we have accessed. However, no security system is impenetrable and we cannot guarantee the security of our database.`,
  },
  {
    title: "Amendment",
    content: `Our Privacy Policy may change from time to time. The most current version of the policy will govern our use of your information and will always be on the website.

Any amendments to this Policy shall be deemed as accepted by the User on their continued use of the website.`,
  },
  {
    title: "Contact Us",
    content: `If you have any questions or concerns regarding this privacy policy, you should contact us by sending an e-mail to:

- sucheta@abybaby.co.in
- shaw.vijay@abybaby.co.in

For consent withdrawal, data download or data removal requests, please email the above addresses.`,
  },
];

function SectionCard({ section, index }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4, delay: index * 0.05 }}
      className="bg-card border border-border rounded-2xl px-5 py-5"
    >
      <div className="flex items-center gap-2 mb-3">
        <div className="w-1 h-4 rounded-full bg-primary flex-shrink-0" />
        <h2
          style={{ fontFamily: "var(--font-heading)" }}
          className="text-sm font-bold text-foreground"
        >
          {section.title}
        </h2>
      </div>
      <p
        style={{ fontFamily: "var(--font-sans)" }}
        className="text-[13px] text-foreground/60 leading-relaxed whitespace-pre-line"
      >
        {section.content}
      </p>
    </motion.div>
  );
}

export function PrivacyPage({ navigate }) {
  return (
    <div className="min-h-screen bg-background">
      {/* ── Mobile top bar ───────────────────────────────────── */}
      <div className="lg:hidden sticky top-0 z-30 bg-card/96 backdrop-blur-sm border-b border-border px-5 h-14 flex items-center justify-between">
        <div
          style={{ fontFamily: "var(--font-heading)" }}
          className="text-lg font-bold text-primary"
        >
          AbyBaby
          <span className="text-foreground/65 ml-1 text-base">Group</span>
        </div>
        <div className="flex items-center gap-1">
          {[...Array(3)].map((_, i) => (
            <div key={i} className="w-1 h-1 rounded-full bg-foreground/40" />
          ))}
        </div>
      </div>

      <div className="max-w-[680px] mx-auto px-5 pt-28 pb-24">
        {/* ── Hero header ──────────────────────────────────────── */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4 }}
          className="mb-8"
        >
          {/* Breadcrumb */}
          <div className="flex items-center gap-1.5 mb-4">
            <button
              onClick={() => navigate("home")}
              style={{ fontFamily: "var(--font-sans)" }}
              className="text-[11px] text-foreground/40 hover:text-primary transition-colors"
            >
              Home
            </button>
            <ChevronRight size={12} className="text-foreground/30" />
            <span
              style={{ fontFamily: "var(--font-sans)" }}
              className="text-[11px] text-primary"
            >
              Privacy Policy
            </span>
          </div>

          {/* Title */}
          <div className="flex items-center gap-3 mb-3">
            <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center flex-shrink-0">
              <Shield size={20} className="text-primary" />
            </div>
            <h1
              style={{ fontFamily: "var(--font-heading)" }}
              className="text-3xl font-bold text-foreground"
            >
              Privacy <span className="text-primary">Policy</span>
            </h1>
          </div>

          <p
            style={{ fontFamily: "var(--font-sans)" }}
            className="text-[13px] text-foreground/50 leading-relaxed"
          >
            This policy is published by{" "}
            <span className="text-foreground/70 font-medium">
              M/s Abybaby E-Com Private Limited
            </span>
            , operating under the brand name{" "}
            <span className="text-primary font-medium">Abybaby Events</span>,
            having its registered address at Ground Floor, 4B, Rani Bhabani
            Road, Kolkata, West Bengal — 700026.
          </p>

          {/* Last updated badge */}
          <div className="mt-4 inline-flex items-center gap-2 bg-primary/8 border border-primary/20 rounded-full px-3 py-1">
            <div className="w-1.5 h-1.5 rounded-full bg-primary" />
            <span
              style={{ fontFamily: "var(--font-sans)" }}
              className="text-[11px] text-primary font-medium"
            >
              In compliance with IT Act, 2000 & GDPR
            </span>
          </div>
        </motion.div>

        {/* ── Intro notice ─────────────────────────────────────── */}
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4, delay: 0.1 }}
          className="bg-primary/5 border border-primary/15 rounded-2xl px-5 py-4 mb-6"
        >
          <p
            style={{ fontFamily: "var(--font-sans)" }}
            className="text-[12px] text-foreground/55 leading-relaxed"
          >
            This electronic record is computer-generated and published in
            accordance with Rule 3(1) of the Information Technology
            (Intermediaries guidelines) Rules, 2011. If you do not agree with
            the terms of our Privacy Policy, please do not use or access the
            site. For questions, contact us at{" "}
            <span className="text-primary">sucheta@abybaby.co.in</span> or{" "}
            <span className="text-primary">shaw.vijay@abybaby.co.in</span>.
          </p>
        </motion.div>

        {/* ── Sections ─────────────────────────────────────────── */}
        <div className="space-y-3">
          {SECTIONS.map((section, i) => (
            <SectionCard key={section.title} section={section} index={i} />
          ))}
        </div>

        {/* ── Footer note ──────────────────────────────────────── */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.4, delay: 0.6 }}
          className="mt-8 text-center"
        >
          <p
            style={{ fontFamily: "var(--font-sans)" }}
            className="text-[11px] text-foreground/30"
          >
            © Abybaby E-Com Private Limited. All rights reserved.
          </p>
        </motion.div>
      </div>
    </div>
  );
}
